#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from syd.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 2 "syd.y"


#include "defs.h"
#include <limits.h>

int error_count=0;

void yyerror(const char *s);
int yyparse();
int yylex();

extern int currLine;
extern int currCol;
extern char *yytext;

#define DEBUG 0

static symbol *new_num_symbol(int value);


#define YY_parse_parse .error verbose /* for better error messages */

#line 26 "syd.y"
typedef union /* all types a grammar symbol can carry */
{
    long long yll; // to check int range
    int yint;
    char  ystr[81];
    struct AstNode_tag *stnode; /* for nonterms that carry an AST node pointer */
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	RETURN	258
#define	BREAK	259
#define	ELSE	260
#define	IF	261
#define	INT	262
#define	WHILE	263
#define	TRUE	264
#define	FALSE	265
#define	GT	266
#define	LT	267
#define	GE	268
#define	LE	269
#define	EQ	270
#define	NE	271
#define	ID	272
#define	NUM	273


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int RETURN;
static const int BREAK;
static const int ELSE;
static const int IF;
static const int INT;
static const int WHILE;
static const int TRUE;
static const int FALSE;
static const int GT;
static const int LT;
static const int GE;
static const int LE;
static const int EQ;
static const int NE;
static const int ID;
static const int NUM;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,RETURN=258
	,BREAK=259
	,ELSE=260
	,IF=261
	,INT=262
	,WHILE=263
	,TRUE=264
	,FALSE=265
	,GT=266
	,LT=267
	,GE=268
	,LE=269
	,EQ=270
	,NE=271
	,ID=272
	,NUM=273


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::RETURN=258;
const int YY_parse_CLASS::BREAK=259;
const int YY_parse_CLASS::ELSE=260;
const int YY_parse_CLASS::IF=261;
const int YY_parse_CLASS::INT=262;
const int YY_parse_CLASS::WHILE=263;
const int YY_parse_CLASS::TRUE=264;
const int YY_parse_CLASS::FALSE=265;
const int YY_parse_CLASS::GT=266;
const int YY_parse_CLASS::LT=267;
const int YY_parse_CLASS::GE=268;
const int YY_parse_CLASS::LE=269;
const int YY_parse_CLASS::EQ=270;
const int YY_parse_CLASS::NE=271;
const int YY_parse_CLASS::ID=272;
const int YY_parse_CLASS::NUM=273;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		118
#define	YYFLAG		-32768
#define	YYNTBASE	30

#define YYTRANSLATE(x) ((unsigned)(x) <= 273 ? yytranslate[x] : 59)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    20,
    21,    28,    26,    22,    27,     2,    29,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    19,     2,
    25,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    23,     2,    24,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     3,     5,     8,    10,    13,    16,    19,    20,
    21,    30,    34,    35,    38,    43,    44,    46,    51,    54,
    55,    58,    59,    64,    71,    75,    79,    85,    86,    89,
    90,    93,    97,   105,   106,   113,   116,   118,   120,   123,
   127,   131,   133,   135,   139,   141,   143,   145,   147,   149,
   151,   153,   157,   159,   161,   163,   167,   169,   171,   173,
   177,   179,   181,   183,   185,   190,   193,   196,   197,   201
};

static const short yyrhs[] = {    31,
     0,     0,     1,     0,    32,    31,     0,    32,     0,    41,
    19,     0,    44,    19,     0,     1,    19,     0,     0,     0,
    37,    17,    33,    20,    35,    21,    34,    38,     0,    36,
    37,    17,     0,     0,     1,    21,     0,    36,    37,    17,
    22,     0,     0,     7,     0,    23,    39,    43,    24,     0,
    40,    41,     0,     0,    40,    41,     0,     0,    37,    17,
    42,    19,     0,    37,    17,    25,    50,    42,    19,     0,
    37,     1,    19,     0,    22,    17,    42,     0,    22,    17,
    25,    50,    42,     0,     0,    43,    44,     0,     0,    47,
    19,     0,     3,    50,    19,     0,     6,    20,    50,    21,
    44,     5,    44,     0,     0,     8,    20,    50,    21,    45,
    44,     0,     4,    19,     0,    46,     0,    19,     0,     1,
    19,     0,    23,    43,    24,     0,    48,    25,    50,     0,
    17,     0,    17,     0,    52,    51,    52,     0,    52,     0,
    14,     0,    12,     0,    11,     0,    13,     0,    15,     0,
    16,     0,    52,    53,    54,     0,    54,     0,    26,     0,
    27,     0,    54,    55,    56,     0,    56,     0,    28,     0,
    29,     0,    20,    50,    21,     0,    48,     0,    18,     0,
     9,     0,    10,     0,    49,    20,    57,    21,     0,    27,
    56,     0,    58,    50,     0,     0,    58,    50,    22,     0,
     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    48,    56,    62,    70,    77,    84,    90,    96,   102,   112,
   120,   132,   146,   153,   161,   172,   179,   185,   192,   200,
   207,   214,   221,   231,   242,   247,   257,   268,   275,   285,
   292,   302,   313,   320,   328,   335,   345,   352,   359,   368,
   375,   382,   390,   401,   408,   415,   422,   429,   436,   443,
   450,   457,   464,   471,   478,   485,   496,   503,   510,   517,
   524,   531,   544,   552,   560,   578,   587,   598,   605,   612
};

static const char * const yytname[] = {   "$","error","$illegal.","RETURN","BREAK",
"ELSE","IF","INT","WHILE","TRUE","FALSE","GT","LT","GE","LE","EQ","NE","ID",
"NUM","';'","'('","')'","','","'{'","'}'","'='","'+'","'-'","'*'","'/'","PROGRAM",
"METH_LIST","METH","@1","@2","PARAMS","FORMALS","TYPE","BODY","DECLS","DECL_LIST",
"DECL","VARS","STMTS","STMT","@3","BLOCK","ASSIGN","LOCATION","METHOD","EXPR",
"RELOP","ADD_EXPR","ADDOP","TERM","MULOP","FACTOR","ACTUALS","ARGS",""
};
#endif

static const short yyr1[] = {     0,
    30,    30,    30,    31,    31,    31,    31,    31,    33,    34,
    32,    35,    35,    35,    36,    36,    37,    38,    39,    39,
    40,    40,    41,    41,    41,    42,    42,    42,    43,    43,
    44,    44,    44,    45,    44,    44,    44,    44,    44,    46,
    47,    48,    49,    50,    50,    51,    51,    51,    51,    51,
    51,    52,    52,    53,    53,    54,    54,    55,    55,    56,
    56,    56,    56,    56,    56,    56,    57,    57,    58,    58
};

static const short yyr2[] = {     0,
     1,     0,     1,     2,     1,     2,     2,     2,     0,     0,
     8,     3,     0,     2,     4,     0,     1,     4,     2,     0,
     2,     0,     4,     6,     3,     3,     5,     0,     2,     0,
     2,     3,     7,     0,     6,     2,     1,     1,     2,     3,
     3,     1,     1,     3,     1,     1,     1,     1,     1,     1,
     1,     3,     1,     1,     1,     3,     1,     1,     1,     3,
     1,     1,     1,     1,     4,     2,     2,     0,     3,     0
};

static const short yydefact[] = {     0,
     3,     0,     0,     0,    17,     0,    42,    38,    30,     1,
     0,     0,     0,     0,    37,     0,     0,     8,    63,    64,
    42,    62,     0,     0,    61,     0,     0,    45,    53,    57,
    36,     0,     0,     0,     0,     4,     0,     9,     6,     7,
    31,     0,     0,    66,    70,    32,    48,    47,    49,    46,
    50,    51,    54,    55,     0,     0,    58,    59,     0,     0,
     0,     0,    40,    29,    25,     0,     0,     0,     0,    41,
    60,     0,     0,    44,    52,    56,     0,    34,    39,    28,
    28,     0,    23,    65,    67,     0,     0,     0,    26,     0,
     0,     0,     0,    69,     0,    35,    28,    24,    14,    10,
     0,    33,    27,     0,    12,    20,    11,    15,    30,     0,
     0,     0,    19,    18,    28,     0,     0,     0
};

static const short yydefgoto[] = {   116,
    10,    11,    68,   104,    92,    93,    12,   107,   109,   110,
    13,    69,    34,    14,    87,    15,    16,    25,    26,    27,
    55,    28,    56,    29,    59,    30,    72,    73
};

static const short yypact[] = {    23,
   -13,   118,    -1,    21,-32768,    29,-32768,-32768,-32768,-32768,
    57,     8,     1,    24,-32768,    31,    27,    36,-32768,-32768,
    39,-32768,   118,   118,-32768,    46,    37,   128,    10,-32768,
-32768,   118,   118,    80,   -13,-32768,    48,    26,-32768,-32768,
-32768,   118,    49,-32768,    50,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,   118,   118,-32768,-32768,   118,    51,
    52,    56,-32768,-32768,-32768,    62,   118,    65,    63,-32768,
-32768,    68,   118,     9,    10,-32768,   114,-32768,-32768,   -15,
    47,     7,-32768,-32768,    70,    85,   114,   118,-32768,    81,
    84,    87,    94,-32768,   114,-32768,    47,-32768,-32768,-32768,
    89,-32768,-32768,    79,    88,   105,-32768,-32768,-32768,    94,
    90,    16,   109,-32768,    -6,   119,   121,-32768
};

static const short yypgoto[] = {-32768,
   112,-32768,-32768,-32768,-32768,-32768,   -78,-32768,-32768,-32768,
    14,   -76,    17,   -33,-32768,-32768,-32768,     0,-32768,   -20,
-32768,    74,-32768,    69,-32768,   -22,-32768,-32768
};


#define	YYLAST		155


static const short yytable[] = {    17,
    64,    44,    43,    89,    90,    18,    66,    91,    37,    88,
    17,    60,    61,   -16,   101,    66,    37,    31,    67,    39,
   103,    70,    -2,     1,    38,     2,     3,   -13,     4,     5,
     6,   112,   115,    17,    53,    54,    76,    57,    58,     7,
    32,     8,    40,    86,   -28,     9,    81,    66,    33,    41,
    67,    42,    85,    96,   -39,    46,    -5,    35,   -43,     2,
     3,   102,     4,     5,     6,    45,    65,    97,    66,    71,
   -68,    77,    78,     7,    79,     8,    17,    64,    80,     9,
    62,    83,     2,     3,    82,     4,    17,     6,    84,    95,
    62,    94,     2,     3,    17,     4,     7,     6,     8,    98,
     5,   106,     9,    63,    99,   105,     7,   100,     8,   108,
    17,   -22,     9,   114,    62,   -21,     2,     3,   117,     4,
   118,     6,    36,   113,    75,   111,    19,    20,    74,     0,
     7,     0,     8,     0,    21,    22,     9,    23,    47,    48,
    49,    50,    51,    52,    24,     0,     0,     0,     0,     0,
     0,     0,     0,    53,    54
};

static const short yycheck[] = {     0,
    34,    24,    23,    80,    81,    19,    22,     1,     1,    25,
    11,    32,    33,     7,    93,    22,     1,    19,    25,    19,
    97,    42,     0,     1,    17,     3,     4,    21,     6,     7,
     8,   110,    17,    34,    26,    27,    59,    28,    29,    17,
    20,    19,    19,    77,    19,    23,    67,    22,    20,    19,
    25,    25,    73,    87,    19,    19,     0,     1,    20,     3,
     4,    95,     6,     7,     8,    20,    19,    88,    22,    21,
    21,    21,    21,    17,    19,    19,    77,   111,    17,    23,
     1,    19,     3,     4,    20,     6,    87,     8,    21,     5,
     1,    22,     3,     4,    95,     6,    17,     8,    19,    19,
     7,    23,    23,    24,    21,    17,    17,    21,    19,    22,
   111,     7,    23,    24,     1,     7,     3,     4,     0,     6,
     0,     8,    11,   110,    56,   109,     9,    10,    55,    -1,
    17,    -1,    19,    -1,    17,    18,    23,    20,    11,    12,
    13,    14,    15,    16,    27,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    26,    27
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 49 "syd.y"
{ 
#if DEBUG
                        printf("Rule #1\n");
#endif 
			TreeRoot=MkNode(astProgram,NULL,yyvsp[0].stnode,NULL,NULL,NULL);
			yyval.stnode=TreeRoot;
                     ;
    break;}
case 2:
#line 57 "syd.y"
{
#if DEBUG
                        printf("Rule #2\n");
#endif
		;
    break;}
case 3:
#line 63 "syd.y"
{
			error_message("Syntax Error","program must have only methods",NULL);
			yyerrok;
			yyclearin;
			yyval.stnode=MkNode(astProgram,NULL,NULL,NULL,NULL,NULL);
		;
    break;}
case 4:
#line 71 "syd.y"
{ 
#if DEBUG
                        printf("Rule #3\n");
#endif 
			yyval.stnode=MkNode(astMethList,NULL,yyvsp[-1].stnode,yyvsp[0].stnode,NULL,NULL);
                     ;
    break;}
case 5:
#line 78 "syd.y"
{ 
#if DEBUG
                        printf("Rule #4\n");
#endif
			yyval.stnode=MkNode(astMethList,NULL,yyvsp[0].stnode,NULL,NULL,NULL);
                     ;
    break;}
case 6:
#line 85 "syd.y"
{
			error_message("Syntax Error","declaration outside of method",NULL);
			yyerrok;
			yyclearin;
		;
    break;}
case 7:
#line 91 "syd.y"
{
			error_message("Syntax Error","statement outside of method",NULL);
			yyerrok;
			yyclearin;
		;
    break;}
case 8:
#line 97 "syd.y"
{
			error_message("Syntax Error","only methods allowed at the top level",NULL);
			yyerrok;
			yyclearin;
		;
    break;}
case 9:
#line 103 "syd.y"
{
#if DEBUG
                        printf("Rule #5 - Part 1\n");
#endif
			addmethod(yyvsp[0].ystr);
			currentscope(yyvsp[0].ystr);
			cur_param_count=0;
			mt[currentmethod].has_return=0;
;
    break;}
case 10:
#line 113 "syd.y"
{ 
#if DEBUG
                        printf("Rule #5 - Part 2\n");
#endif
			mt[currentmethod].param_count=cur_param_count;
 		;
    break;}
case 11:
#line 120 "syd.y"
{
#if DEBUG
                        printf("Rule #5 - Part 3\n");
#endif
			if(!mt[currentmethod].has_return){
				error_message("Semantic Error","method doesn't have return value",mt[currentmethod].name);
			}
			symbol *temps=new_symbol(yyvsp[-6].ystr);
			yyval.stnode=MkNode(astMethod,temps,yyvsp[-3].stnode,yyvsp[0].stnode,NULL,NULL);
			leavescope();
			;
    break;}
case 12:
#line 133 "syd.y"
{ 
#if DEBUG
                        printf("Rule #6\n");
#endif
			if(findsymb(&mt[currentmethod].ht,yyvsp[0].ystr)){
				error_message("Semantic Error","duplicate parameter in method",yyvsp[0].ystr);
			}
			addvariable(yyvsp[0].ystr,TRUE_VAL);
			cur_param_count++;
			symbol *temps=new_symbol(yyvsp[0].ystr);
			AstNode *parameter=MkNode(astParam,temps,NULL,NULL,NULL,NULL);
			yyval.stnode=MkNode(astParam,NULL,yyvsp[-2].stnode,parameter,NULL,NULL);
                     ;
    break;}
case 13:
#line 147 "syd.y"
{ 
#if DEBUG
                        printf("Rule #7\n");
#endif
			yyval.stnode=MkNode(astParams,NULL,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 14:
#line 154 "syd.y"
{
#if DEBUG
                        printf("Rule #8\n");
			fprintf(stderr,"Skipping parameters.\n");
#endif
			yyerrok;
		;
    break;}
case 15:
#line 162 "syd.y"
{ 
#if DEBUG
                        printf("Rule #9\n");
#endif
			addvariable(yyvsp[-1].ystr,TRUE_VAL);
			cur_param_count++;
			symbol *temps=new_symbol(yyvsp[-1].ystr);
			AstNode *parameter=MkNode(astParam,temps,NULL,NULL,NULL,NULL);
			yyval.stnode=MkNode(astParam,NULL,yyvsp[-3].stnode,parameter,NULL,NULL);
                     ;
    break;}
case 16:
#line 173 "syd.y"
{ 
#if DEBUG
                        printf("Rule #10\n");
#endif
			yyval.stnode=NULL;
                     ;
    break;}
case 17:
#line 180 "syd.y"
{ 
#if DEBUG
                        printf("Rule #11\n");
#endif
                     ;
    break;}
case 18:
#line 186 "syd.y"
{ 
#if DEBUG
                        printf("Rule #12\n");
#endif
			yyval.stnode=MkNode(astBody,NULL,yyvsp[-2].stnode,yyvsp[-1].stnode,NULL,NULL);
                     ;
    break;}
case 19:
#line 193 "syd.y"
{ 
#if DEBUG
                        printf("Rule #13\n");
#endif
			yyval.stnode=MkNode(astBody,NULL,yyvsp[-1].stnode,yyvsp[0].stnode,NULL,NULL);

                     ;
    break;}
case 20:
#line 201 "syd.y"
{ 
#if DEBUG
                        printf("Rule #14\n");
#endif
			yyval.stnode=MkNode(astBody,NULL,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 21:
#line 208 "syd.y"
{ 
#if DEBUG
                        printf("Rule #15\n");
#endif
			yyval.stnode=MkNode(astDecls,NULL,yyvsp[-1].stnode,yyvsp[0].stnode,NULL,NULL);
                     ;
    break;}
case 22:
#line 215 "syd.y"
{ 
#if DEBUG
                        printf("Rule #16\n");
#endif
			yyval.stnode=NULL;
                     ;
    break;}
case 23:
#line 222 "syd.y"
{ 
#if DEBUG
                        printf("Rule #17\n");
#endif
			addvariable(yyvsp[-2].ystr,FALSE_VAL);
			symbol *temps=new_symbol(yyvsp[-2].ystr);
			AstNode *var=MkNode(astVarList,temps,NULL,NULL,NULL,NULL);
			yyval.stnode=MkNode(astDecls,NULL,var,yyvsp[-1].stnode,NULL,NULL);
                     ;
    break;}
case 24:
#line 232 "syd.y"
{ 
#if DEBUG
                        printf("Rule #18\n");
#endif
			addvariable(yyvsp[-4].ystr,FALSE_VAL);
			symbol *temps=new_symbol(yyvsp[-4].ystr);
			AstNode *init=MkNode(astAssign,NULL,MkNode(astId, findsymbolinmethod(yyvsp[-4].ystr), NULL,NULL,NULL,NULL),yyvsp[-2].stnode,NULL,NULL);
			AstNode *var=MkNode(astVarList,temps,init,NULL,NULL,NULL);
			yyval.stnode=MkNode(astDecls,NULL,var,yyvsp[-1].stnode,NULL,NULL);
                     ;
    break;}
case 25:
#line 243 "syd.y"
{
			yyerrok;
			yyval.stnode=MkNode(astDecls,NULL,NULL,NULL,NULL,NULL);
		;
    break;}
case 26:
#line 248 "syd.y"
{ 
#if DEBUG
                        printf("Rule #19\n");
#endif
			addvariable(yyvsp[-1].ystr,FALSE_VAL);
			symbol *temps=new_symbol(yyvsp[-1].ystr);
			AstNode *var=MkNode(astVarList,temps,NULL,NULL,NULL,NULL);
			yyval.stnode=MkNode(astDecls,NULL,var,yyvsp[0].stnode,NULL,NULL);
                     ;
    break;}
case 27:
#line 258 "syd.y"
{ 
#if DEBUG
                        printf("Rule #20\n");
#endif
			addvariable(yyvsp[-3].ystr,FALSE_VAL);
			symbol *temps=new_symbol(yyvsp[-3].ystr);
			AstNode *init=MkNode(astAssign,NULL,MkNode(astId, findsymbolinmethod(yyvsp[-3].ystr), NULL,NULL,NULL,NULL),yyvsp[-1].stnode,NULL,NULL);
			AstNode *var=MkNode(astVarList,temps,init,NULL,NULL,NULL);
			yyval.stnode=MkNode(astDecls,NULL,var,yyvsp[0].stnode,NULL,NULL);
                     ;
    break;}
case 28:
#line 269 "syd.y"
{ 
#if DEBUG
                        printf("Rule #21\n");
#endif
			yyval.stnode=NULL;
                     ;
    break;}
case 29:
#line 276 "syd.y"
{ 
#if DEBUG
                        printf("Rule #22\n");
#endif
			if(ast_returns(yyvsp[-1].stnode)){
				error_message("Semantic Error","cannot reach code after return",mt[currentmethod].name);
			}
			yyval.stnode=MkNode(astStmtSeq,NULL,yyvsp[-1].stnode,yyvsp[0].stnode,NULL,NULL);
                     ;
    break;}
case 30:
#line 286 "syd.y"
{ 
#if DEBUG
                        printf("Rule #23\n");
#endif
			yyval.stnode=MkNode(astStmtSeq,NULL,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 31:
#line 293 "syd.y"
{ 
#if DEBUG
                        printf("Rule #24\n");
#endif
			if(!yyvsp[-1].stnode || !is_location(yyvsp[-1].stnode->pAstNode[0])){
				error_message("Semantic Error","assignment target is not a variable",NULL);
			}
			yyval.stnode=MkNode(astExprStmt,NULL,yyvsp[-1].stnode,NULL,NULL,NULL);
                     ;
    break;}
case 32:
#line 303 "syd.y"
{ 
#if DEBUG
                        printf("Rule #25\n");
#endif
			if(currentmethod==-1){
				error_message("Semantic Error","return outside of a method",NULL);
			}			
			mt[currentmethod].has_return=1;
			yyval.stnode=MkNode(astReturnStmt,NULL,yyvsp[-1].stnode,NULL,NULL,NULL);
                     ;
    break;}
case 33:
#line 314 "syd.y"
{ 
#if DEBUG
                        printf("Rule #26\n");
#endif
			yyval.stnode=MkNode(astIfElseStmt,NULL,yyvsp[-4].stnode,yyvsp[-2].stnode,yyvsp[0].stnode,NULL);
                     ;
    break;}
case 34:
#line 321 "syd.y"
{ 
#if DEBUG
                        printf("Rule #27 - Part 1\n");
#endif
			loopdepth++;
		;
    break;}
case 35:
#line 328 "syd.y"
{
#if DEBUG
                        printf("Rule #27 - Part 2\n");
#endif
			loopdepth--;
			yyval.stnode=MkNode(astWhileStmt,NULL,yyvsp[-3].stnode,yyvsp[0].stnode,NULL,NULL);
                     ;
    break;}
case 36:
#line 336 "syd.y"
{ 
#if DEBUG
                        printf("Rule #28\n");
#endif
			if(loopdepth==0){
				error_message("Semantic Error","break outside of loop",NULL);
			}
			yyval.stnode=MkNode(astBreakStmt,NULL,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 37:
#line 346 "syd.y"
{ 
#if DEBUG
                        printf("Rule #29\n");
#endif
			yyval.stnode=yyvsp[0].stnode;
                     ;
    break;}
case 38:
#line 353 "syd.y"
{ 
#if DEBUG
                        printf("Rule #30\n");
#endif
			yyval.stnode=MkNode(astNullStmt,NULL,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 39:
#line 360 "syd.y"
{
#if DEBUG
                        printf("Rule #31\n");
			fprintf(stderr,"Skipping statement.\n");
#endif
			yyerrok;
			yyval.stnode=MkNode(astNullStmt,NULL,NULL,NULL,NULL,NULL);
		;
    break;}
case 40:
#line 369 "syd.y"
{ 
#if DEBUG
                        printf("Rule #32\n");
#endif
			yyval.stnode=MkNode(astBlock,NULL,yyvsp[-1].stnode,NULL,NULL,NULL);
                     ;
    break;}
case 41:
#line 376 "syd.y"
{ 
#if DEBUG
                        printf("Rule #33\n");
#endif
			yyval.stnode=MkNode(astAssign,NULL,yyvsp[-2].stnode,yyvsp[0].stnode,NULL,NULL);
                     ;
    break;}
case 42:
#line 383 "syd.y"
{ 
#if DEBUG
                        printf("Rule #34\n");
#endif
			symbol *temps=findsymbolinmethod(yyvsp[0].ystr);
			yyval.stnode=MkNode(astId,temps,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 43:
#line 391 "syd.y"
{ 
#if DEBUG
                        printf("Rule #35\n");
#endif
			if(methodidx(yyvsp[0].ystr)==-1){
				error_message("Semantic Error","undeclared method",yyvsp[0].ystr);
			}
			symbol *temps=new_symbol(yyvsp[0].ystr);
			yyval.stnode=MkNode(astId,temps,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 44:
#line 402 "syd.y"
{ 
#if DEBUG
                        printf("Rule #36\n");
#endif
			yyval.stnode=MkNode(yyvsp[-1].stnode->NodeType,NULL,yyvsp[-2].stnode,yyvsp[0].stnode,NULL,NULL);
                     ;
    break;}
case 45:
#line 409 "syd.y"
{ 
#if DEBUG
                        printf("Rule #37\n");
#endif
			yyval.stnode=yyvsp[0].stnode;
                     ;
    break;}
case 46:
#line 416 "syd.y"
{ 
#if DEBUG
                        printf("Rule #38\n");
#endif
			yyval.stnode=MkNode(astLeEq,NULL,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 47:
#line 423 "syd.y"
{ 
#if DEBUG
                        printf("Rule #39\n");
#endif
			yyval.stnode=MkNode(astLess,NULL,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 48:
#line 430 "syd.y"
{ 
#if DEBUG
                        printf("Rule #40\n");
#endif
			yyval.stnode=MkNode(astGreater,NULL,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 49:
#line 437 "syd.y"
{ 
#if DEBUG
                        printf("Rule #41\n");
#endif
			yyval.stnode=MkNode(astGrEq,NULL,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 50:
#line 444 "syd.y"
{ 
#if DEBUG
                        printf("Rule #42\n");
#endif
			yyval.stnode=MkNode(astEq,NULL,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 51:
#line 451 "syd.y"
{ 
#if DEBUG
                        printf("Rule #43\n");
#endif
			yyval.stnode=MkNode(astNotEq,NULL,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 52:
#line 458 "syd.y"
{ 
#if DEBUG
                        printf("Rule #44\n");
#endif
			yyval.stnode=MkNode(yyvsp[-1].stnode->NodeType,NULL,yyvsp[-2].stnode,yyvsp[0].stnode,NULL,NULL);
                     ;
    break;}
case 53:
#line 465 "syd.y"
{ 
#if DEBUG
                        printf("Rule #45\n");
#endif
			yyval.stnode=yyvsp[0].stnode;
                     ;
    break;}
case 54:
#line 472 "syd.y"
{ 
#if DEBUG
                        printf("Rule #46\n");
#endif
			yyval.stnode=MkNode(astAdd,NULL,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 55:
#line 479 "syd.y"
{ 
#if DEBUG
                        printf("Rule #47\n");
#endif
			yyval.stnode=MkNode(astSub,NULL,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 56:
#line 486 "syd.y"
{ 
#if DEBUG
                        printf("Rule #48\n");
#endif
			if(yyvsp[-1].stnode->NodeType==astDiv){
			    if(is_zero(yyvsp[0].stnode))
				error_message("Semantic Error","division by zero",NULL);
			}
			yyval.stnode=MkNode(yyvsp[-1].stnode->NodeType,NULL,yyvsp[-2].stnode,yyvsp[0].stnode,NULL,NULL);
                     ;
    break;}
case 57:
#line 497 "syd.y"
{ 
#if DEBUG
                        printf("Rule #49\n");
#endif
			yyval.stnode=yyvsp[0].stnode;
                     ;
    break;}
case 58:
#line 504 "syd.y"
{ 
#if DEBUG
                        printf("Rule #50\n");
#endif
			yyval.stnode=MkNode(astMult,NULL,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 59:
#line 511 "syd.y"
{ 
#if DEBUG
                        printf("Rule #51\n");
#endif
			yyval.stnode=MkNode(astDiv,NULL,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 60:
#line 518 "syd.y"
{ 
#if DEBUG
                        printf("Rule #52\n");
#endif
			yyval.stnode=yyvsp[-1].stnode;
                     ;
    break;}
case 61:
#line 525 "syd.y"
{ 
#if DEBUG
                        printf("Rule #53\n");
#endif
			yyval.stnode=yyvsp[0].stnode;
                     ;
    break;}
case 62:
#line 532 "syd.y"
{ 
#if DEBUG
                        printf("Rule #54\n");
#endif
			if(yyvsp[0].yll<INT_MIN || yyvsp[0].yll>INT_MAX){
				error_message("Semantic Error","numeric constant out of range",NULL);
				yyval.stnode=MkNode(astDecimConst,NULL,NULL,NULL,NULL,NULL);
			} else{
				symbol *temps=new_num_symbol((int)yyvsp[0].yll);
				yyval.stnode=MkNode(astDecimConst,temps,NULL,NULL,NULL,NULL);
			}
                     ;
    break;}
case 63:
#line 545 "syd.y"
{ 
#if DEBUG
                        printf("Rule #55\n");
#endif
			symbol *temps=new_num_symbol(1);
			yyval.stnode=MkNode(astDecimConst,temps,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 64:
#line 553 "syd.y"
{ 
#if DEBUG
                        printf("Rule #56\n");
#endif
			symbol *temps=new_num_symbol(0);
			yyval.stnode=MkNode(astDecimConst,temps,NULL,NULL,NULL,NULL);
                     ;
    break;}
case 65:
#line 561 "syd.y"
{ 
#if DEBUG
                        printf("Rule #57\n");
#endif
			if(!yyvsp[-3].stnode || !yyvsp[-3].stnode->SymbolNode){
				error_message("Semantic Error","method symbol missing in call",(char*)yyvsp[-3].stnode->SymbolNode->name);
			}
			int mi=methodidx((char*)yyvsp[-3].stnode->SymbolNode->name);
			if(mi==-1){
				error_message("Semantic Error","undeclared method",(char*)yyvsp[-3].stnode->SymbolNode->name);
			}
			int ca=count_args(yyvsp[-1].stnode);
			if(ca != mt[mi].param_count){
				error_message("Syntax Error","method needs different type of arguments",mt[mi].name);
			}
			yyval.stnode=MkNode(astCall,NULL,yyvsp[-3].stnode,yyvsp[-1].stnode,NULL,NULL);
                     ;
    break;}
case 66:
#line 579 "syd.y"
{
#if DEBUG
		printf("Rule #57-Unary Minus\n");
#endif
		symbol *temps=new_num_symbol(0);
		yyval.stnode=MkNode(astSub,NULL,MkNode(astDecimConst,temps,NULL,NULL,NULL,NULL),yyvsp[0].stnode,NULL,NULL);
		;
    break;}
case 67:
#line 588 "syd.y"
{ 
#if DEBUG
                        printf("Rule #58\n");
#endif
			if(yyvsp[-1].stnode==NULL){
				yyval.stnode=MkNode(astArgs,NULL,yyvsp[0].stnode,NULL,NULL,NULL);
			}else{
			        yyval.stnode = MkNode(astArgs, NULL, yyvsp[-1].stnode, MkNode(astArgs, NULL, yyvsp[0].stnode, 				NULL, NULL, NULL), NULL, NULL);
			}
                     ;
    break;}
case 68:
#line 599 "syd.y"
{ 
#if DEBUG
                        printf("Rule #59\n");
#endif
			yyval.stnode=NULL;
                     ;
    break;}
case 69:
#line 606 "syd.y"
{ 
#if DEBUG
                        printf("Rule #60\n");
#endif
			yyval.stnode=MkNode(astArgs,NULL,yyvsp[-2].stnode,MkNode(astArgs,NULL,yyvsp[-1].stnode,NULL,NULL,NULL),NULL,NULL);
                     ;
    break;}
case 70:
#line 613 "syd.y"
{ 
#if DEBUG
                        printf("Rule #61\n");
#endif
			yyval.stnode=NULL;
                     ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 619 "syd.y"


/* creates symbols with int instead of char* */
static symbol *new_num_symbol(int value) {
    char buf[32];
    snprintf(buf, sizeof(buf), "%d", value);
    symbol *s = new_symbol(buf);  
    s->timi = value;
    return s;
}


void yyerror(const char *s)
{
   error_message("Syntax Error",s,NULL);
}

/* int main(void)
{
   if(yyparse()==0){
	int mi=methodidx("main");
	if(mi==-1){
		error_message("Syntax Error","need to have main method",NULL);
	}
	if(mt[mi].param_count != 0){
		error_message("Syntax Error","main cannot have parameters",NULL);
	}
	fflush(stdout);
	if(error_count==0){
		printAST(TreeRoot, -3);
	} else {
		fprintf(stderr,"Parsing failed.\n");
	}
   }
} */


#include "syd2.y"
